'''13.Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be: 
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four 
million, write a program to find the sum of the even-valued terms.
'''

odd=0
even=1
total = 0
while True:
	#finding the odd numbers
    odd = odd + even  
    #finding the even numbers
    even = odd + even 
    if even < 4000000: 
        total += even 
    else:
        break
print total
